<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">

    <xacro:property name="footprint_radius" value="0.001" />
    <!-- 1.添加base_footprint -->
    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="${footprint_radius}" />
            </geometry>
        </visual>
    </link>

    <!-- 2.添加底盘 -->
    <!-- 
        形状：圆柱
        半径：0.1m
        高度：0.08m
        离地间距：0.015m
     -->
    <xacro:property name="base_radius" value="0.1" />
    <xacro:property name="base_length" value="0.08" />
    <xacro:property name="lidi" value="0.015" />
    <xacro:property name="base_joint_z" value="" />
    <!-- 2-1.link -->
    <link name="base_link">
        <visual>
            <geometry>
                <cylinder length="${base_length}" radius="${base_radius}" />
            </geometry>

            <origin xyz="0.0 0.0 0" rpy="0.0 0.0 0.0" />

            <material name="baselink_color">
                <color rgba="1.0 0.5 0.2 0.5" />
            </material>
        </visual>
    </link>

    <!-- 2-2.joint -->
    <joint name="link2footprint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <!-- z的偏移量=离地间距+base_link高度的一半=0.04+0.015=0.055 -->
        <!-- 如果这个偏移量设置为0，然后在base_link中设置z的偏移量为0.055，也可以得到一样的效果；但不建议这么做，因为相对坐标会重合。 -->
        <!-- 要求，在正常情况下，每个link的偏移都设置为0； -->
        <origin xyz="0.0 0.0 0.055" rpy="0.0 0.0 0.0" />
    </joint>

    <!-- 3.添加驱动轮 -->
    <!-- 驱动轮属性 -->
    <!-- 
        形状:圆柱
        半径:0.0325m
        长度:0.015m
     -->
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_length" value="0.015" />
    <!-- 驱动轮宏实现 -->
    <xacro:macro name="add_wheels" params="name flag">
        <link name="${name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
                <material name="black" />
            </visual>
        </link>
        <joint name="${name}2base" type="continuous">
            <parent link="base_link" />
            <child link="${name}_wheel" />
            <!-- 
                x 无偏移
                y 车体的半径
                z =车体高度 / 2 + 离地间距 - 车轮半径=0.055-0.0325=0.0255m
            -->
            <origin xyz="0.0 ${flag * base_radius} ${-(lidi + )}" rpy="0.0 0.0 0.0" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>
    <!-- 3-1.link -->

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.0325" length="0.015" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="1.5708 0.0 0.0" />
            <material name="right_wheel_color">
                <color rgba="0.0 0.0 0.0 0.3" />
            </material>
        </visual>
    </link>
    <!-- 3-2.joint -->
    <joint name="left2link" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel" />
        <!-- 
            x 无偏移
            y 车体的半径
            z =车体高度 / 2 + 离地间距 - 车轮半径=0.055-0.0325=0.0255m
         -->
        <origin xyz="0.0 0.1 -0.0255" rpy="0.0 0.0 0.0" />
        <axis xyz="0 1 0" />
    </joint>
    <joint name="right2link" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />
        <!-- 
            x 无偏移
            y 车体的半径
            z =车体高度 / 2 + 离地间距 - 车轮半径=0.055-0.0325=0.0255m
         -->
        <origin xyz="0.0 -0.1 -0.0255" rpy="0.0 0.0 0.0" />
        <axis xyz="0 1 0" />
    </joint>


</robot>